env:
  global:
    - secure: "NUOLTtE3hoBVoy0empIq+e0iwNH7QrAdze6ne12MK/shgCmX0m8crsdisS1bXH0xt6UQyD2KgVdVDLODJOKTPYF9ya8Ql1pFY01sEy2J5w1mjwtwJKp/H4jj36Fa6zb2ERCsNOuMWFbdylTwoxkBvUwsO1iaNYt7+cNMkdqrEXSiZugPVqHGLpdS6dgFA/Yis69jfnql5OpECs3woKvab0nLyg1sCYYpdo4knowfgCIaAaJeznakq0x62cceFnfxxJTo3I3Ng1+3ySNGyPBpjmofPqHRNa/OnaAmGrtRTAWHzoxL3J2sPycqwv2UlPfoSi3ZMcrx+CKvgyxKKWAdZU832Fwuxs2qaQOmy18g0v77IK3knBbZd/4iCMUsuiwRJ6KR6n7Xv6HyUCn9Hj3A2KJmPM8scY6sdHPMPfFD7zVUZyPYBqghuLvn8DsF/x1xzDezEkVuT8ZNOLr9YqCTS3z1nsr1w/54vcYB/+NSKwlftsMajAte3dqD0sssZKi0A402UyI+LxkrEgZOhUqW0m/8AnMlIpgGAPUKlK9Ew7hTZNJbc55yVNC2SN4YF16kCe8x9IoVbOvKHH5ZCCnibEe2zXlUjDyE2//jhTaQ+w2/B4Ae8VCCv81fI7iOaYtkvnl1dudGuD3y75XJOwKlMekeC/GjOnf66JtXOw+CM0Q="
    - DOCKER_USER="wxdlong"
    - IMAGE="gocker"



services:
  - docker


before_install:
  - echo "before install"

install:
  - echo "install"
  - docker build -t ${DOCKER_USER}/${IMAGE} .

script:
  - echo "$DOCKER_PWD" | docker login -u "${DOCKER_USER}" --password-stdin
  - docker images
  - docker push ${DOCKER_USER}/${IMAGE}

after_success:
  - echo "after_success"