name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
      run: |
        echo "ACCESS_TOKEN: ${ACCESS_TOKEN:0-9:9}"
        docker login docker.pkg.github.com -u wxdlong -p ${ACCESS_TOKEN}
        docker build . --file Dockerfile --tag docker.pkg.github.com/wxdlong/gocker
        docker push docker.pkg.github.com/wxdlong/gocker
      
